language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.2-linux64.tar.xz
  - tar xf arduino-1.8.2-linux64.tar.xz
  - sudo mv arduino-1.8.2 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  # Add the esp8266 to the boardmanager <- basically download the appropriate compilers
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  # Manually add the Arduino JSON Library to the correct folder
  - git clone https://github.com/bblanchon/ArduinoJson /usr/local/share/arduino/libraries/ArduinoJson
  # Use the Arduino IDE to add some required libraries
  - arduino --install-library "DHT sensor library,Adafruit Unified Sensor,PubSubClient"
  # Install the ESP board files
  - arduino --install-boards esp8266:esp8266 --save-prefs
  - arduino --board esp8266:esp8266:generic:CpuFrequency=80,FlashFreq=40,FlashMode=dio,UploadSpeed=921600,FlashSize=4M3M,ResetMethod=ck --save-prefs
  - arduino --pref "compiler.warning_level=all" --save-prefs
  - arduino --pref build.path=${TRAVIS_BUILD_DIR}/src/WiFiSensor/build --save-prefs
  - mkdir -p ${TRAVIS_BUILD_DIR}/src/WiFiSensor/build
script:
  - "echo $PWD"
  - "echo $HOME"
  - "ls $PWD"
  #- source $TRAVIS_BUILD_DIR/travis/common.sh
  - "echo Starting the Build"
  - arduino --verbose --verify ${TRAVIS_BUILD_DIR}/src/WiFiSensor/WiFiSensor.ino
after_success:
  #
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: UHnbT2eHXWHisD8xH07NA94hkaptkHdC9PeuPUppdBsb4a0rcVTrr0pKHBReiz8m6YFIaYd///iXl07QJxRJAoHxV/mNTAguCTYsJtzcRuIjzJTO6CTN9XTLbzF8XWgTCpYCBpeFsTpO9jXxnO3QSFLPP4KnSQEuihLv3wErd0+CfSpTP3pU/ITsEz1MzC0NJzwuUhNeESYzeGiwo91LPLmEWsG2SyQodXgDvHpr97p62TOY2cdqMVAgB0AdatK03GjtnRH0G8jvEamFW4F3fWBSvAllAh1Z63hZo9D2Cx/9sHj3/0ApDubepXtfKecWpVlcbsRLQiXmuE3VuxKcA+j9xUlRNX09oPmQ/1QgYi6aOJwZHrZ+0nY66KMHN9ZHRgXOl3h8qQDi6wZK66sI4T2m0NLG4rfr2mylcB93P0g5IZWQ4s4MPo/pcBg4tB6zXwLF5s7QS8Ifhme9DL5N4mXyUmvIL5r0R3OpV/z2SqduNDaxTe13JuZ4NymmOnomrw0UMMA5q3D9E5bAxRW8CqmWJ2vEOdZPkxY5rOwzXvP/fQU+vSg8XgSWJ0fNWslxIKij0+MWy5BqzbN/OJpUeqaXDlnfOq4KmI6UdhctKjQZAVleXu+pKem21c9L3MgmQ+UcY55lvHs6G1KOMkisp/rHV+4J8iOEg5QWKDoWlJU=
  file: '/home/travis/build/brickmen/WiFiSensor/src/WiFiSensor/build/WiFiSensor.ino.bin'
  on:
    tags: true
    repo: brickmen/WiFiSensor
